import React, {useState} from 'react';
import SiteHeader from '../components/SiteHeader';
import {Button, Field, Input} from '../editor/ui';
import BBSS from '../editor/story-settings';
import {createProject, projectHref} from '../services/projects';
export default function NewProject() {
  const [form, setForm] = useState({name: '', author: '', size: 'A4', orientation: 'Vertical', length: '32 pages', style: 'Storybook Illustration', pageNums: true, aesthetic: ''}), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const set = (k,v) => setForm(f => ({...f,[k]:v}));
  const submit = async e => {e.preventDefault(); if (!form.name.trim()) {setError('Give your storybook a name.'); return;} setBusy(true); setError(''); try {const id = await createProject({...form, name: form.name.trim()}); location.assign(projectHref(id));} catch {setError('The book could not be saved. Check your browser storage and try again.'); setBusy(false);}};
  return <div className="site-page"><SiteHeader/><main className="setup-page"><a href="/home">Back to my storybooks</a><p className="eyebrow">Every story begins somewhere</p><h1>Let’s make your storybook.</h1><p>Set the stage. You can change these details as your story grows.</p><form onSubmit={submit}><section className="setup-card"><h2>The beginning</h2><Field label="Storybook name" error={error}><Input maxLength={100} autoFocus placeholder="Give your story a title" value={form.name} onChange={e => set('name',e.target.value)} required/></Field><Field label="Author (optional)"><Input maxLength={100} placeholder="Your name" value={form.author} onChange={e => set('author',e.target.value)}/></Field></section><section className="setup-card"><div className="subrow"><h2>Page setup</h2><BBSS.OrientationToggle value={form.orientation} onChange={v => set('orientation',v)}/></div><BBSS.SizeGrid value={form.size} orientation={form.orientation} onChange={v => set('size',v)}/><h3>Book length</h3><BBSS.LengthPicker value={form.length} onChange={v => set('length',v)}/><label className="checkrow"><input type="checkbox" checked={form.pageNums} onChange={e => set('pageNums',e.target.checked)}/>Include page numbers</label></section><section className="setup-card"><h2>A world of your own</h2><p>Choose an illustration direction. Sample artwork is a placeholder.</p><BBSS.StyleGrid value={form.style} onChange={v => set('style',v)}/><Field label="Desired aesthetic (optional)"><textarea className="ui-textarea" rows={3} placeholder="Warm summer evenings, a touch of magic…" value={form.aesthetic} onChange={e => set('aesthetic',e.target.value)}/></Field></section><div className="setup-footer"><p>Creates a blank book on this device.</p><Button type="submit" disabled={busy}>{busy ? 'Creating…' : 'Create storybook'}</Button></div></form></main></div>;
}
