import React, {useState} from 'react';
import {Button, Dialog, DialogHeader, DialogTitle, DialogDescription, DialogFooter, Field} from '../editor/ui';
import {Icon} from '../editor/icons';
export function ExportDialog({pages, settings, dims, theme, onClose, serverPdfHref}) {
  const formats = serverPdfHref ? ['Finished book PDF','PDF','PNG images','Print PDF'] : ['PDF','PNG images','Print PDF'];
  const [format,setFormat] = useState(formats[0]), [scope,setScope] = useState('All pages'), [from,setFrom] = useState(1), [to,setTo] = useState(pages.length), [quality,setQuality] = useState('High'), [cover,setCover] = useState(true), [bleed,setBleed] = useState(false), [busy,setBusy] = useState(false), [progress,setProgress] = useState(0), [done,setDone] = useState(false), [error,setError] = useState('');
  const isServerPdf = format === 'Finished book PDF';
  const validRange = Number.isInteger(+from) && Number.isInteger(+to) && from >= 1 && to <= pages.length && +to >= +from;
  const selected = (scope === 'All pages' ? pages : validRange ? pages.slice(+from-1,+to) : []).filter(p => cover || p.kind !== 'cover');
  const run = async () => {
    // The finished-book PDF is the real, generated book from the pipeline —
    // just open the server link so the browser downloads it directly.
    if (isServerPdf) {window.open(serverPdfHref, '_blank', 'noopener'); setDone(true); return;}
    setBusy(true);setError('');setProgress(0);try {const {exportBook} = await import('../services/export');await exportBook({pages:selected,settings,dims,theme,format,quality,bleed:bleed&&format==='Print PDF',onProgress:setProgress});setDone(true);} catch(e) {setError(e.message || 'Export failed. Please try again.');} finally {setBusy(false);}};
  const select = (label,value,set,options) => <Field label={label}><select className="ui-select ex-select" value={value} onChange={e=>set(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></Field>;
  return <Dialog open onOpenChange={() => !busy && onClose()} label="Export book"><DialogHeader><DialogTitle>Export book</DialogTitle><DialogDescription>Download “{settings.name}” as a finished file.</DialogDescription></DialogHeader>{done ? <div className="empty-state"><Icon name="circle-check" size={40}/><h2>Your book has been exported</h2><p>{selected.length} pages · {format === 'PNG images' ? 'PNG images in a ZIP file' : format}</p><Button variant="outline" onClick={run} disabled={busy}>{busy ? 'Exporting…' : 'Download again'}</Button></div> : busy ? <div className="empty-state" aria-busy="true"><Icon name="loader" className="spin" size={28}/><p>Rendering your pages… {progress}%</p><progress className="export-progress" max={100} value={progress}/></div> : <>{select('Format',format,setFormat,formats)}{isServerPdf ? <p className="muted">Downloads the finished book that was generated on the server — text and art baked in, ready to print or share.</p> : <>{select('Pages',scope,setScope,['All pages','Range'])}{scope==='Range' && <div className="ex-range"><Field label="From page"><input className="ui-input" type="number" min={1} max={pages.length} value={from} onChange={e=>setFrom(e.target.value)}/></Field><span>to</span><Field label="To page"><input className="ui-input" type="number" min={1} max={pages.length} value={to} onChange={e=>setTo(e.target.value)}/></Field></div>}{scope==='Range' && !validRange && <p className="form-error" role="alert">Enter a valid range between 1 and {pages.length}.</p>}{select('Quality',quality,setQuality,['Standard','High','Print 300dpi'])}<label className="ex-row"><span>Include cover</span><input type="checkbox" checked={cover} onChange={e=>setCover(e.target.checked)}/></label>{format==='Print PDF' && <><label className="ex-row"><span>Include crop marks</span><input type="checkbox" checked={bleed} onChange={e=>setBleed(e.target.checked)}/></label><p className="muted">Crop marks use a 6 mm outer margin. Artwork bleed and CMYK conversion require a print-production service.</p></>}</>}</>}{error && <p role="alert" className="export-error">{error}</p>}<DialogFooter><span className="ex-summary">{selected.length} pages</span><Button variant="outline" disabled={busy} onClick={onClose}>{done?'Done':'Cancel'}</Button>{!done && <Button onClick={run} disabled={busy||!selected.length}>Export</Button>}</DialogFooter></Dialog>;
}
export function ShareDialog({settings,onClose,onExport}) {
  return <Dialog open onOpenChange={onClose} label="Share a read-only link"><DialogHeader><DialogTitle>Share a read-only link</DialogTitle><DialogDescription>Let someone step into “{settings.name}”.</DialogDescription></DialogHeader><div className="disabled-note"><Icon name="link"/><p>Online sharing isn’t connected yet. This book is stored only in your browser, so a public link cannot be created.</p><p>Export your book as a PDF to share a read-only copy now.</p></div><Field label="Who can open it"><select className="ui-select" disabled><option>Available when online sharing is connected</option></select></Field><DialogFooter><Button variant="outline" onClick={onClose}>Done</Button><Button onClick={onExport}><Icon name="download"/>Export a copy</Button></DialogFooter></Dialog>;
}
